### PR TITLE
Don't force save before download if notebook isn't writable

### LINKED ISSUE #1112: cannot "download as IPython notebook" a read-only notebook
When I open a read-only ipython notebook I cannot download it as an ipynb file, even if it hasn't been modified.

Steps to reproduce:
  1. make some existing `*.ipynb` file readonly on your file system
  2. open it with jupyter notebook (the editor will flash "auto-save disabled" and show a small logo "this notebook is read-only")
  3. select   File > Download as > IPython notebook (*.ipynb) (this just opens a blank page, does not download anything, and shows no error on the console)

Context: I'm trying to setup a public Jupyter installation where users can test some of my tools.  In this installation I have some example notebooks that I have marked as read-only because I don't want them to be modified by mistake, but I'd still like them to be downloadable.

### PR DESCRIPTION
**Pull request by minrk**
closes #1112

### CODE REVIEW

**Comment by takluyver** [comment]
It appears that Travis failed to see this, for some reason.

File: notebook/static/notebook/js/menubar.js [hunk 1]
```diff
@@ -79,7 +79,7 @@ define([
         ) + "?download=" + download.toString();
         
         var w = window.open('', IPython._target);
-        if (this.notebook.dirty) {
+        if (this.notebook.dirty && that.notebook.writable) {
```
Comment (takluyver) [inline notebook/static/notebook/js/menubar.js]: I think it should be `this` instead of `that`.

Comment (Carreau) [inline notebook/static/notebook/js/menubar.js]: Yep.
