### PR TITLE
Fix move selection up/down

### LINKED ISSUE #793: Move cell up and down inconsistant.
do not work with multiple selection (we can decide that how it works though), 
but imho it should move blocks. 

Or implementation side, move the cell before the block after the block when move up,  and vice versa. (Though it might unbind callbacks)

### PR DESCRIPTION
**Pull request by Carreau**
Move the selection by detach/attach previous/next cell, and reselect the
moved selection.

Closes #793 (once test written).

### CODE REVIEW

File: notebook/static/notebook/js/notebook.js [hunk 1]
```diff
@@ -840,6 +840,53 @@ define(function (require) {
...
+     * No op if the selection is at the beginning of the notebook
+     */
+    Notebook.prototype.move_selection_up = function(){
+        // actually will move the cell before the selection, after the selection
+        var indices = this.get_selected_cells_indices();
+        var first = indices[0];
+        var last = indices[indices.length-1];
+
+        var i1 = this.get_selected_index();
+        var i2 = this.get_anchor_index();
```
Comment (captainsafia) [inline notebook/static/notebook/js/notebook.js]: Can these variable names be a little bit more descriptive? Currently, the code is a little bit hard to read.

**Comment by minrk** [comment]
Tested and works as advertised. Great job on 4.1, @Carreau!
