### PR TITLE
Change the tab renderer to allow adding closable tab

### LINKED ISSUE #6476: Close icon is not displayed on new tab
**Describe the bug**
The close icon do not appear when adding a new closable tab in the main area (`TabPanel`).

**To Reproduce**
Create an extension which add a new widget in the main area, something like :
```
widget = new MainAreaWidget({content});
widget.id = 'new_widget';
widget.title.label = 'Courses';
widget.title.closable = true;

let w = app.shell.widgets('main').next() as TabPanel;
w.addWidget(widget);
```

**Expected behavior**
Have a close symbol on the tab, like :
image

**Screenshots**
Currently the result is :
image

### PR DESCRIPTION
**Pull request by brichet**
This PR add a `close` icon on new closable tab in `tree-extension`.

Fix #6476

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @brichet this can also be useful for https://github.com/jupyter/notebook/pull/6316.

File: packages/tree-extension/src/index.ts [hunk 1]
```diff
@@ -3,19 +3,19 @@
 
 import {
   JupyterFrontEnd,
-  JupyterFrontEndPlugin
+  JupyterFrontEndPlugin,
```
Comment (jtpio) [inline packages/tree-extension/src/index.ts:6]: Were these prettier changes added automatically on commit?

Comment (brichet) [reply packages/tree-extension/src/index.ts:6]: Yes, I couldn't commit because of prettier check, so I ran `jlpm prettier` and add the changes.
But the command did have change a lot of files, with the same kind of modification.

Comment (brichet) [reply packages/tree-extension/src/index.ts]: Thanks @jtpio, I had some weird file in `node-modules/.bin`.
`jlpm clean` did the trick.

**Review by jtpio — APPROVED** [review]
Thanks!
